services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: reddylohith
      MYSQL_DATABASE: simplyfly_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - simplyfly-network

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/simplyfly_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: reddylohith
    networks:
      - simplyfly-network

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - simplyfly-network

volumes:
  mysql_data:

networks:
  simplyfly-network:
